// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0oaJltNP4p1p6-dJ8YR5tWJEr4U9qU1c',
    appId: '1:171231676222:web:a7d4e46fc231724b218e6f',
    messagingSenderId: '171231676222',
    projectId: 'mehalat-store',
    authDomain: 'mehalat-store.firebaseapp.com',
    storageBucket: 'mehalat-store.firebasestorage.app',
    measurementId: 'G-9JFRR7X4SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN8dwx_ynj6j7cQfneDUYw78veTpZwcyY',
    appId: '1:171231676222:android:53438da65b3a07ba218e6f',
    messagingSenderId: '171231676222',
    projectId: 'mehalat-store',
    storageBucket: 'mehalat-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhLAuED6iLxn_IE-QYGugRKXhTYObKP3A',
    appId: '1:171231676222:ios:3ec52fc55f6a7aa8218e6f',
    messagingSenderId: '171231676222',
    projectId: 'mehalat-store',
    storageBucket: 'mehalat-store.firebasestorage.app',
    androidClientId: '171231676222-67q1c1q8i0ac0dsb9u27o2p50joj3rrt.apps.googleusercontent.com',
    iosClientId: '171231676222-h9irgu5uj735gb5vrpk3938h5pqt98l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehalat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhLAuED6iLxn_IE-QYGugRKXhTYObKP3A',
    appId: '1:171231676222:ios:3ec52fc55f6a7aa8218e6f',
    messagingSenderId: '171231676222',
    projectId: 'mehalat-store',
    storageBucket: 'mehalat-store.firebasestorage.app',
    androidClientId: '171231676222-67q1c1q8i0ac0dsb9u27o2p50joj3rrt.apps.googleusercontent.com',
    iosClientId: '171231676222-h9irgu5uj735gb5vrpk3938h5pqt98l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehalat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0oaJltNP4p1p6-dJ8YR5tWJEr4U9qU1c',
    appId: '1:171231676222:web:b5a222eb50f27fc8218e6f',
    messagingSenderId: '171231676222',
    projectId: 'mehalat-store',
    authDomain: 'mehalat-store.firebaseapp.com',
    storageBucket: 'mehalat-store.firebasestorage.app',
    measurementId: 'G-GP6DTNW85K',
  );

}